expiry_date: "2021-05-06 22:00:00"
title: "Register to vote"
preamble: >
  <p>Register to vote to get on the electoral register, or to change your details.</p>
  <p>You need to be on the electoral register to vote in elections or referendums.</p>

faqs:
  - question: Related content
    answer: >
      <a href="/register-to-vote?src=actions">Register to vote</a>
      <a href="/how-to-vote?src=actions">How to vote</a>
      <a href="/how-to-vote?src=actions#voting-by-proxy">Ask someone to vote for you</a>

  - question: Deadline for registering to vote in the 6 May 2021 elections
    answer: >
      <p>You can no longer register to vote in the elections on 6 May. You can still register for future elections.</p>

  - question: Who can register
    answer: >
      <p>You must be aged 16 or over (or 14 or over in Scotland and Wales).</p>
      <p>You must also be one of the following:</p>
      <ul>
        <li>a British citizen</li>
        <li>an Irish or EU citizen living in the UK</li>
        <li>a Commonwealth citizen who has permission to enter or stay in the UK, or who does not need permission</li>
        <li>a citizen of another country living in Scotland or Wales who has permission to enter or stay in the UK, or who does not need permission</li>
      </ul>
      <p>Check which <a href="/elections-in-the-uk?src=schema">elections you’re eligible to vote in</a>.</p>

  - question: Register online
    answer: >
      <p>It usually takes about 5 minutes.</p>
      <p><a rel="external" href="https://www.registertovote.service.gov.uk/register-to-vote/start?src=schema">Start now</a></p>
      <h2>What you need to know</h2>
      <p>You’ll be asked for your National Insurance number (but you can still register if you do not have one).</p>
      <p>After you’ve registered, your name and address will appear on the electoral register.</p>

  - question: Check if you’re already registered
    answer: >
      <p><a href="/contact-electoral-registration-office?src=schema">Contact your local Electoral Registration Office</a> to find out if you’re already registered to vote.</p>

  - question: Update your registration
    answer: >
      <p>You can also use the <a rel="external" href="https://www.registertovote.service.gov.uk/register-to-vote/start?src=schema">‘Register to vote’ service</a> to:</p>
      <ul>
        <li>change your name, address or nationality</li>
        <li>get on or off the <a href="/electoral-register?src=schema">open register</a></li>
      </ul>
      <p>To do this, you need to register again with your new details (even if you’re already registered to vote).</p>

  - question: Registering with a paper form
    answer: >
      <p>You can <a href="/government/publications/register-to-vote-if-youre-living-in-the-uk?src=schema">register using a paper form in England, Wales and Scotland</a>.</p>
      <p>You’ll need to print, fill out and <a href="/contact-electoral-registration-office?src=schema">send the form to your local Electoral Registration Officer</a>.</p>

  - question: If you live abroad
    answer: >
      <p>You can use this service to <a rel="external" href="https://www.registertovote.service.gov.uk/register-to-vote/start?src=schema">register to vote</a> (or to renew or update your registration) if you:</p>
      <ul>
        <li>are a British citizen</li>
        <li>were registered to vote within the last 15 years (or, in some cases, if you were too young to register when you were in the UK)</li>
      </ul>
      <p>You may need your passport details.</p>

  - question: If you’re a public servant posted overseas
    answer: >
      <p>There’s a different service for public servants (and their spouses and civil partners) who are posted overseas as:</p>
      <ul>
        <li><a href="/register-to-vote-crown-servants-british-council-employees?src=schema">Crown servants or British council employees</a></li>
        <li>members of the <a href="/register-to-vote-armed-forces?src=schema">armed forces</a>
      </li>
      </ul>

  - question: Get help registering
    answer: >
      <p>You can get help registering from your local <a href="/get-on-electoral-register?src=schema">Electoral Registration Office</a>.</p>
